Run_loot_table = {
{["loot_id"] = "19345", ["loot_name"] = " Aegis of Preservation ", ["prio"] = " Prio:Pri",},
{["loot_id"] = "20928", ["loot_name"] = " Qiraj Bindings of Command ", ["prio"] = " Prio: Rog, Fur, Tnk > Other PC",},
{["loot_id"] = "20932", ["loot_name"] = " Qiraj Bindings of Dominance ", ["prio"] = " Prio: Mag, Wlk > Other PC",},
{["loot_id"] = "20930", ["loot_name"] = " Vek'lor Diadem ", ["prio"] = " Prio: Rog > Other PC",},
{["loot_id"] = "20926", ["loot_name"] = " Vek'nilash's Circlet ", ["prio"] = " Prio: Mag, Wlk, Tnk",},
{["loot_id"] = "20927", ["loot_name"] = " Ouro's Intact Hide ", ["prio"] = " Prio: Fur,Tnk",},
{["loot_id"] = "20931", ["loot_name"] = " Skin of the Great Sandworm ", ["prio"] = " Prio: Open",},
{["loot_id"] = "20929", ["loot_name"] = " Carapace of the Old God ", ["prio"] = " Prio: Rog, Fur, Tnk",},
{["loot_id"] = "20933", ["loot_name"] = " Husk of the Old God ", ["prio"] = " Prio: Mag,Wlk",},
{["loot_id"] = "21232", ["loot_name"] = " Imperial Qiraj Armament ", ["prio"] = " Prio: Rog, Fur, Tnk",},
{["loot_id"] = "21232", ["loot_name"] = " Imperial Qiraji Regalia ", ["prio"] = " Prio: Mag, Wlk",},
{["loot_id"] = "18823", ["loot_name"] = " Aged Core Leather Gloves ", ["prio"] = " Prio:Rog, Tnk",},
{["loot_id"] = "21702", ["loot_name"] = " Amulet of Foul Warding ", ["prio"] = " Prio:Frl, Hnt, Rog, War",},
{["loot_id"] = "21608", ["loot_name"] = " Amulet of Vek'nilash ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "17067", ["loot_name"] = " Ancient Cornerstone Grimoire ", ["prio"] = " Prio:Dru, Mag, Pri, Pal, Wlk",},
{["loot_id"] = "18703", ["loot_name"] = " Ancient Petrified Leaf ", ["prio"] = " Prio:Hnt",},
{["loot_id"] = "21650", ["loot_name"] = " Ancient Qiraji Ripper ", ["prio"] = " Prio:Rog, War",},
{["loot_id"] = "21690", ["loot_name"] = " Angelista's Charm ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "19388", ["loot_name"] = " Angelista's Grasp ", ["prio"] = " Prio:Dru, Mag, Pri, Pal, Wlk",},
{["loot_id"] = "21695", ["loot_name"] = " Angelista's Touch ", ["prio"] = " Prio:Frl, War",},
{["loot_id"] = "21837", ["loot_name"] = " Anubisath Warhammer ", ["prio"] = " Prio:War",},
{["loot_id"] = "19336", ["loot_name"] = " Arcane Infused Gem ", ["prio"] = " Prio:Hnt",},
{["loot_id"] = "19376", ["loot_name"] = " Archimtiros' Ring of Reckoning ", ["prio"] = " Prio:Frl, Hnt, Rog, Pal, War",},
{["loot_id"] = "19361", ["loot_name"] = " Ashjre'thul, Crossbow of Smiting ", ["prio"] = " Prio:Hnt",},
{["loot_id"] = "19364", ["loot_name"] = " Ashkandi, Greatsword of the Brotherhood ", ["prio"] = " Prio:Hnt, War",},
{["loot_id"] = "17105", ["loot_name"] = " Aurastone Hammer ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "17103", ["loot_name"] = " Azuresong Mageblade ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "21670", ["loot_name"] = " Badge of the Swarmguard ", ["prio"] = " Prio:Hnt, Rog, War",},
{["loot_id"] = "17063", ["loot_name"] = " Band of Accuria ", ["prio"] = " Prio:Hnt, Rog, War",},
{["loot_id"] = "19434", ["loot_name"] = " Band of Dark Dominion ", ["prio"] = " Prio:Wlk",},
{["loot_id"] = "19403", ["loot_name"] = " Band of Forced Concentration ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "22961", ["loot_name"] = " Band of Reanimation ", ["prio"] = " Prio:Hnt",},
{["loot_id"] = "19138", ["loot_name"] = " Band of Sulfuras ", ["prio"] = " Prio:Dru, Mag, Pri, Pal, Wlk",},
{["loot_id"] = "23031", ["loot_name"] = " Band of the Inevitable ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "22939", ["loot_name"] = " Band of Unanswered Prayers ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "23038", ["loot_name"] = " Band of Unnatural Forces ", ["prio"] = " Prio:Rog, War",},
{["loot_id"] = "21635", ["loot_name"] = " Barb of the Sand Reaver ", ["prio"] = " Prio:Hnt",},
{["loot_id"] = "21664", ["loot_name"] = " Barbed Choker ", ["prio"] = " Prio:Hnt, Rog, War",},
{["loot_id"] = "21699", ["loot_name"] = " Barrage Shoulders ", ["prio"] = " Prio:Hnt",},
{["loot_id"] = "21708", ["loot_name"] = " Beetle Scaled Wristguards ", ["prio"] = " Prio:Frl, Hnt, Rog, War",},
{["loot_id"] = "21586", ["loot_name"] = " Belt of Never-ending Agony ", ["prio"] = " Prio:Rog",},
{["loot_id"] = "21682", ["loot_name"] = " Bile-Covered Gauntlets ", ["prio"] = " Prio:Frl, Rog",},
{["loot_id"] = "19399", ["loot_name"] = " Black Ash Robe ", ["prio"] = " Prio:Dru, Mag, Pri, Sha, Wlk",},
{["loot_id"] = "19373", ["loot_name"] = " Black Brood Pauldrons ", ["prio"] = " Prio:Hnt",},
{["loot_id"] = "17072", ["loot_name"] = " Blastershot Launcher ", ["prio"] = " Prio:Rog, War",},
{["loot_id"] = "17076", ["loot_name"] = " Bonereaver's Edge ", ["prio"] = " Prio: Rank 8+",},
{["loot_id"] = "23073", ["loot_name"] = " Boots of Displacement ", ["prio"] = " Prio:Frl, Rog",},
{["loot_id"] = "21600", ["loot_name"] = " Boots of Epiphany ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "19437", ["loot_name"] = " Boots of Pure Thought ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "21688", ["loot_name"] = " Boots of the Fallen Hero ", ["prio"] = " Prio: Tnk > War",},
{["loot_id"] = "21705", ["loot_name"] = " Boots of the Fallen Prophet ", ["prio"] = " Prio:??",},
{["loot_id"] = "19381", ["loot_name"] = " Boots of the Shadow Flame ", ["prio"] = " Prio:Rog",},
{["loot_id"] = "21706", ["loot_name"] = " Boots of the Unwavering Will ", ["prio"] = " Prio:War",},
{["loot_id"] = "21604", ["loot_name"] = " Bracelets of Royal Redemption ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "19374", ["loot_name"] = " Bracers of Arcane Accuracy ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "21814", ["loot_name"] = " Breastplate of Annihilation ", ["prio"] = " Prio:War",},
{["loot_id"] = "22800", ["loot_name"] = " Brimstone Staff ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "18832", ["loot_name"] = " Brutality Blade ", ["prio"] = " Prio:Rog",},
{["loot_id"] = "21697", ["loot_name"] = " Cape of the Trinity ", ["prio"] = " Prio:Bal, Mag, Pri, Ele, Wlk",},
{["loot_id"] = "19140", ["loot_name"] = " Cauterizing Band ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "17109", ["loot_name"] = " Choker of Enlightenment ", ["prio"] = " Prio:Dru, Mag, Pri, Pal, Wlk",},
{["loot_id"] = "18814", ["loot_name"] = " Choker of the Fire Lord ", ["prio"] = " Prio:Mag, Shd, Wlk",},
{["loot_id"] = "19387", ["loot_name"] = " Chromatic Boots ", ["prio"] = " Prio:War",},
{["loot_id"] = "19352", ["loot_name"] = " Chromatically Tempered Sword ", ["prio"] = " Prio: Rog/Fur",},
{["loot_id"] = "19432", ["loot_name"] = " Circle of Applied Force ", ["prio"] = " Prio:Frl, Hnt, Rog, War",},
{["loot_id"] = "19347", ["loot_name"] = " Claw of Chromaggus ", ["prio"] = " Prio:Dru, Mag, Pri, Pal, Wlk",},
{["loot_id"] = "19365", ["loot_name"] = " Claw of the Black Drake ", ["prio"] = " Prio:Hnt, Rog, War",},
{["loot_id"] = "23242", ["loot_name"] = " Claw of the Frost Wyrm ", ["prio"] = " Prio:Hnt, War",},
{["loot_id"] = "22813", ["loot_name"] = " Claymore of Unholy Might ", ["prio"] = " Prio:Hnt, War",},
{["loot_id"] = "21583", ["loot_name"] = " Cloak of Clarity ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "21701", ["loot_name"] = " Cloak of Concentrated Hatred ", ["prio"] = " Prio:Rog, War",},
{["loot_id"] = "19436", ["loot_name"] = " Cloak of Draconic Might ", ["prio"] = " Prio:War",},
{["loot_id"] = "19398", ["loot_name"] = " Cloak of Firemaw ", ["prio"] = " Prio:Hnt, Rog, War",},
{["loot_id"] = "22960", ["loot_name"] = " Cloak of Suturing ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "19378", ["loot_name"] = " Cloak of the Brood Lord ", ["prio"] = " Prio:Mag, Shd, Wlk",},
{["loot_id"] = "22731", ["loot_name"] = " Cloak of the Devoured ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "21621", ["loot_name"] = " Cloak of the Golden Hive ", ["prio"] = " Prio: Tnk > War",},
{["loot_id"] = "23050", ["loot_name"] = " Cloak of the Necropolis ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "23030", ["loot_name"] = " Cloak of the Scourge ", ["prio"] = " Prio:Frl, Hnt, Rog, War",},
{["loot_id"] = "17102", ["loot_name"] = " Cloak of the Shrouded Mists ", ["prio"] = " Prio:Hnt, Rog, Tnk",},
{["loot_id"] = "21627", ["loot_name"] = " Cloak of Untold Secrets ", ["prio"] = " Prio:Wlk",},
{["loot_id"] = "18806", ["loot_name"] = " Core Forged Greaves ", ["prio"] = " Prio:War",},
{["loot_id"] = "18805", ["loot_name"] = " Core Hound Tooth ", ["prio"] = " Prio:Rog, War",},
{["loot_id"] = "22691", ["loot_name"] = " Corrupted Ashbringer ", ["prio"] = " Prio:War (PvP)",},
{["loot_id"] = "21669", ["loot_name"] = " Creeping Vine Helm ", ["prio"] = " Prio:Dru, Pal",},
{["loot_id"] = "17077", ["loot_name"] = " Crimson Shocker ", ["prio"] = " Prio:Mag, Pri, Wlk",},
{["loot_id"] = "18817", ["loot_name"] = " Crown of Destruction ", ["prio"] = " Prio:Hnt, Pal, War",},
{["loot_id"] = "19363", ["loot_name"] = " Crul'shorukh, Edge of Chaos ", ["prio"] = " Prio:War",},
{["loot_id"] = "22938", ["loot_name"] = " Cryptfiend Silk Cloak ", ["prio"] = " Prio:War",},
{["loot_id"] = "23220", ["loot_name"] = " Crystal Webbed Robe ", ["prio"] = " Prio:Bal, Mag, Pri, Wlk",},
{["loot_id"] = "21134", ["loot_name"] = " Dark Edge of Insanity ", ["prio"] = " Prio: Rank 8+",},
{["loot_id"] = "21585", ["loot_name"] = " Dark Storm Gauntlets ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "23075", ["loot_name"] = " Death's Bargain ", ["prio"] = " Prio:Pal",},
{["loot_id"] = "21126", ["loot_name"] = " Death's Sting ", ["prio"] = " Prio:Rog",},
{["loot_id"] = "18829", ["loot_name"] = " Deep Earth Spaulders ", ["prio"] = " Prio:Pal",},
{["loot_id"] = "22994", ["loot_name"] = " Digested Hand of Power ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "21615", ["loot_name"] = " Don Rigoberto's Lost Hat ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "19362", ["loot_name"] = " Doom's Edge ", ["prio"] = " Prio:War",},
{["loot_id"] = "22821", ["loot_name"] = " Doomfinger ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "19354", ["loot_name"] = " Draconic Avenger ", ["prio"] = " Prio:Hnt, War",},
{["loot_id"] = "19358", ["loot_name"] = " Draconic Maul ", ["prio"] = " Prio:Frl",},
{["loot_id"] = "17107", ["loot_name"] = " Dragon's Blood Cape ", ["prio"] = " Prio:Frl, War",},
{["loot_id"] = "19367", ["loot_name"] = " Dragon's Touch ", ["prio"] = " Prio:Mag, Pri, Wlk",},
{["loot_id"] = "19368", ["loot_name"] = " Dragonbreath Hand Cannon ", ["prio"] = " Prio:Hnt, Rog, War",},
{["loot_id"] = "19346", ["loot_name"] = " Dragonfang Blade ", ["prio"] = " Prio:Rog, Tnk",},
{["loot_id"] = "19406", ["loot_name"] = " Drake Fang Talisman ", ["prio"] = " Prio:Rog, War",},
{["loot_id"] = "19353", ["loot_name"] = " Drake Talon Cleaver ", ["prio"] = " Prio:Hnt, War",},
{["loot_id"] = "19394", ["loot_name"] = " Drake Talon Pauldrons ", ["prio"] = " Prio:War",},
{["loot_id"] = "17066", ["loot_name"] = " Drillborer Disk ", ["prio"] = " Prio:War",},
{["loot_id"] = "17073", ["loot_name"] = " Earthshaker ", ["prio"] = " Prio:Pal, War",},
{["loot_id"] = "19407", ["loot_name"] = " Ebony Flame Gloves ", ["prio"] = " Prio:Shd, Wlk",},
{["loot_id"] = "19349", ["loot_name"] = " Elementium Reinforced Bulwark ", ["prio"] = " Prio: Tnk > Fur",},
{["loot_id"] = "19386", ["loot_name"] = " Elementium Threaded Cloak ", ["prio"] = " Prio:Frl, War",},
{["loot_id"] = "19433", ["loot_name"] = " Emberweave Leggings ", ["prio"] = " Prio:Hnt, War",},
{["loot_id"] = "19385", ["loot_name"] = " Empowered Leggings ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "18203", ["loot_name"] = " Eskhandar's Right Claw ", ["prio"] = " Prio:War",},
{["loot_id"] = "19435", ["loot_name"] = " Essence Gatherer ", ["prio"] = " Prio:Mag, Pri, Wlk",},
{["loot_id"] = "18815", ["loot_name"] = " Essence of the Pure Flame ", ["prio"] = " Prio:Frl, War",},
{["loot_id"] = "21221", ["loot_name"] = " Eye of C'Thun ", ["prio"] = " Prio:Mag, Wlk, Tnk",},
{["loot_id"] = "23001", ["loot_name"] = " Eye of Diminution ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "23047", ["loot_name"] = " Eye of the Dead ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "22730", ["loot_name"] = " Eyestalk Waist Cord ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "21647", ["loot_name"] = " Fetish of the Sand Reaver ", ["prio"] = " Prio:Mag, War",},
{["loot_id"] = "18803", ["loot_name"] = " Finkle's Lava Dredger ", ["prio"] = " Prio:Dru, Pal",},
{["loot_id"] = "19142", ["loot_name"] = " Fire Runed Grimoire ", ["prio"] = " Prio:Dru, Mag, Pri, Pal, Wlk",},
{["loot_id"] = "19139", ["loot_name"] = " Fireguard Shoulders ", ["prio"] = " Prio:Frl, Rog, War",},
{["loot_id"] = "19400", ["loot_name"] = " Firemaw's Clutch ", ["prio"] = " Prio:Bal, Mag, Pri, Pal, Wlk",},
{["loot_id"] = "18811", ["loot_name"] = " Fireproof Cloak ", ["prio"] = " Prio:Dru, Mag, Pri, Pal, Wlk",},
{["loot_id"] = "19143", ["loot_name"] = " Flameguard Gauntlets ", ["prio"] = " Prio:War",},
{["loot_id"] = "18861", ["loot_name"] = " Flamewaker Legplates ", ["prio"] = " Prio:War",},
{["loot_id"] = "21838", ["loot_name"] = " Garb of Royal Ascension ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "21581", ["loot_name"] = " Gauntlets of Annihilation ", ["prio"] = " Prio: War > Tnk",},
{["loot_id"] = "21624", ["loot_name"] = " Gauntlets of Kalimdor ", ["prio"] = " Prio:Pal",},
{["loot_id"] = "21674", ["loot_name"] = " Gauntlets of Steadfast Determination ", ["prio"] = " Prio:War",},
{["loot_id"] = "22937", ["loot_name"] = " Gem of Nerubis ", ["prio"] = " Prio:Bal, Mag, Pri, Wlk",},
{["loot_id"] = "23057", ["loot_name"] = " Gem of Trapped Innocents ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "23226", ["loot_name"] = " Ghoul Skin Tunic ", ["prio"] = " Prio:Frl, War",},
{["loot_id"] = "23663", ["loot_name"] = " Girdle of Elemental Fury ", ["prio"] = " Prio:??",},
{["loot_id"] = "23219", ["loot_name"] = " Girdle of the Mentor ", ["prio"] = " Prio:War",},
{["loot_id"] = "23032", ["loot_name"] = " Glacial Headdress ", ["prio"] = " Prio:Mag, Pri, Wlk",},
{["loot_id"] = "22968", ["loot_name"] = " Glacial Mantle ", ["prio"] = " Prio:Mag, Pri, Wlk",},
{["loot_id"] = "21689", ["loot_name"] = " Gloves of Ebru ", ["prio"] = " Prio:Bal, Pal",},
{["loot_id"] = "21672", ["loot_name"] = " Gloves of Enforcement ", ["prio"] = " Prio:Rog",},
{["loot_id"] = "19369", ["loot_name"] = " Gloves of Rapid Evolution ", ["prio"] = " Prio:Dru, Pri, Sha",},
{["loot_id"] = "21605", ["loot_name"] = " Gloves of the Hidden Temple ", ["prio"] = " Prio:Frl",},
{["loot_id"] = "18808", ["loot_name"] = " Gloves of the Hypnotic Flame ", ["prio"] = " Prio:Mag",},
{["loot_id"] = "21888", ["loot_name"] = " Gloves of the Immortal ", ["prio"] = " Prio:Mag, Pri, Wlk",},
{["loot_id"] = "21619", ["loot_name"] = " Gloves of the Messiah ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "22981", ["loot_name"] = " Gluth's Missing Collar ", ["prio"] = " Prio:War",},
{["loot_id"] = "23040", ["loot_name"] = " Glyph of Deflection ", ["prio"] = " Prio:War",},
{["loot_id"] = "21607", ["loot_name"] = " Grasp of the Fallen Emperor ", ["prio"] = " Prio:??",},
{["loot_id"] = "21582", ["loot_name"] = " Grasp of the Old God ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "23054", ["loot_name"] = " Gressil, Dawn of Ruin ", ["prio"] = " Prio:Rog, War",},
{["loot_id"] = "21693", ["loot_name"] = " Guise of the Devourer ", ["prio"] = " Prio:Frl",},
{["loot_id"] = "17071", ["loot_name"] = " Gutgore Ripper ", ["prio"] = " Prio:Rog",},
{["loot_id"] = "23028", ["loot_name"] = " Hailstone Band ", ["prio"] = " Prio:All",},
{["loot_id"] = "21703", ["loot_name"] = " Hammer of Ji'zhi ", ["prio"] = " Prio:Dru, Pal",},
{["loot_id"] = "23056", ["loot_name"] = " Hammer of the Twisting Nether ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "23044", ["loot_name"] = " Harbinger of Doom ", ["prio"] = " Prio:Hnt, Rog, Tnk",},
{["loot_id"] = "22816", ["loot_name"] = " Hatchet of Sundered Bone ", ["prio"] = " Prio:War",},
{["loot_id"] = "19002", ["loot_name"] = " Head of Nefarian ", ["prio"] = " Prio:Frl, Hnt, Rog, Pal, War",},
{["loot_id"] = "18879", ["loot_name"] = " Heavy Dark Iron Ring ", ["prio"] = " Prio:Frl, War",},
{["loot_id"] = "19372", ["loot_name"] = " Helm of Endless Rage ", ["prio"] = " Prio: Tnk > Fur",},
{["loot_id"] = "18870", ["loot_name"] = " Helm of the Lifegiver ", ["prio"] = " Prio:Pal",},
{["loot_id"] = "19357", ["loot_name"] = " Herald of Woe ", ["prio"] = " Prio:Frl",},
{["loot_id"] = "21618", ["loot_name"] = " Hive Defiler Wristguards ", ["prio"] = " Prio:War",},
{["loot_id"] = "21645", ["loot_name"] = " Hive Tunneler's Boots ", ["prio"] = " Prio:Frl",},
{["loot_id"] = "21616", ["loot_name"] = " Huhuran's Stinger ", ["prio"] = " Prio:Hnt, Rog, War",},
{["loot_id"] = "23014", ["loot_name"] = " Iblis, Blade of the Fallen Seraph ", ["prio"] = " Prio:Rog, War",},
{["loot_id"] = "23019", ["loot_name"] = " Icebane Helmet ", ["prio"] = " Prio:War",},
{["loot_id"] = "22940", ["loot_name"] = " Icebane Pauldrons ", ["prio"] = " Prio:War",},
{["loot_id"] = "23033", ["loot_name"] = " Icy Scale Coif ", ["prio"] = " Prio:Hnt",},
{["loot_id"] = "22967", ["loot_name"] = " Icy Scale Spaulders ", ["prio"] = " Prio:Hnt",},
{["loot_id"] = "22399", ["loot_name"] = " Idol of Health ", ["prio"] = " Prio:Dru",},
{["loot_id"] = "21232", ["loot_name"] = " Imperial Qiraji Armaments ", ["prio"] = " Prio:Frl, Rog, War",},
{["loot_id"] = "21237", ["loot_name"] = " Imperial Qiraji Regalia ", ["prio"] = " Prio:Dru, Mag, Pri, Wlk",},
{["loot_id"] = "19439", ["loot_name"] = " Interlaced Shadow Jerkin ", ["prio"] = " Prio:Dru, Hnt, Rog, War",},
{["loot_id"] = "23570", ["loot_name"] = " Jom Gabbar ", ["prio"] = " Prio:Hnt, Rog, War",},
{["loot_id"] = "21679", ["loot_name"] = " Kalimdor's Revenge ", ["prio"] = " Prio:War (PvP)",},
{["loot_id"] = "22802", ["loot_name"] = " Kingsfall ", ["prio"] = " Prio:Rog, Tnk",},
{["loot_id"] = "22954", ["loot_name"] = " Kiss of the Spider ", ["prio"] = " Prio:Rog, War",},
{["loot_id"] = "23557", ["loot_name"] = " Larvae of the Great Worm ", ["prio"] = " Prio:Hnt, Rog, War",},
{["loot_id"] = "23071", ["loot_name"] = " Leggings of Apocalypse ", ["prio"] = " Prio:Frl, Hnt, Rog, War",},
{["loot_id"] = "23665", ["loot_name"] = " Leggings of Elemental Fury ", ["prio"] = " Prio:?",},
{["loot_id"] = "21698", ["loot_name"] = " Leggings of Immersion ", ["prio"] = " Prio:Dru, Pal",},
{["loot_id"] = "23070", ["loot_name"] = " Leggings of Polarity ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "21676", ["loot_name"] = " Leggings of the Festering Swarm ", ["prio"] = " Prio:Mag",},
{["loot_id"] = "23068", ["loot_name"] = " Legplates of Carnage ", ["prio"] = " Prio:War",},
{["loot_id"] = "19341", ["loot_name"] = " Lifegiving Gem ", ["prio"] = " Prio:War",},
{["loot_id"] = "23042", ["loot_name"] = " Loatheb's Reflection ", ["prio"] = " Prio:All",},
{["loot_id"] = "19360", ["loot_name"] = " Lok'amir il Romathis ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "22804", ["loot_name"] = " Maexxna's Fang ", ["prio"] = " Prio:Hnt, Rog, Tnk",},
{["loot_id"] = "19351", ["loot_name"] = " Maladath, Runed Blade of the Black Flight ", ["prio"] = " Prio: Tnk > Rog/Fur",},
{["loot_id"] = "19405", ["loot_name"] = " Malfurion's Blessed Bulwark ", ["prio"] = " Prio:Frl, War",},
{["loot_id"] = "22943", ["loot_name"] = " Malice Stone Pendant ", ["prio"] = " Prio:Bal, Mag, Pri, Wlk",},
{["loot_id"] = "17106", ["loot_name"] = " Malistar's Defender ", ["prio"] = " Prio:Pal",},
{["loot_id"] = "19136", ["loot_name"] = " Mana Igniting Cord ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "18872", ["loot_name"] = " Manastorm Leggings ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "21686", ["loot_name"] = " Mantle of Phrenic Power ", ["prio"] = " Prio:Mag",},
{["loot_id"] = "19370", ["loot_name"] = " Mantle of the Blackwing Cabal ", ["prio"] = " Prio:Mag, Shd, Wlk",},
{["loot_id"] = "21683", ["loot_name"] = " Mantle of the Desert's Fury ", ["prio"] = " Prio:Pal?",},
{["loot_id"] = "21665", ["loot_name"] = " Mantle of Wicked Revenge ", ["prio"] = " Prio:Frl, Fur",},
{["loot_id"] = "22732", ["loot_name"] = " Mark of C'Thun ", ["prio"] = " Prio:Frl, War",},
{["loot_id"] = "22809", ["loot_name"] = " Maul of the Redeemed Crusader ", ["prio"] = " Prio:Pal",},
{["loot_id"] = "17065", ["loot_name"] = " Medallion of Steadfast Might ", ["prio"] = " Prio:Frl, War",},
{["loot_id"] = "19375", ["loot_name"] = " Mish'undare, Circlet of the Mind Flayer ", ["prio"] = " Prio: Mag,Wlk",},
{["loot_id"] = "22803", ["loot_name"] = " Midnight Haze ", ["prio"] = " Prio:Bal, Mag, Pri, Wlk",},
{["loot_id"] = "22798", ["loot_name"] = " Might of Menethil ", ["prio"] = " Prio:War",},
{["loot_id"] = "19339", ["loot_name"] = " Mind Quickening Gem ", ["prio"] = " Prio:Mag",},
{["loot_id"] = "23221", ["loot_name"] = " Misplaced Servo Arm ", ["prio"] = " Prio:Rog, War",},
{["loot_id"] = "19344", ["loot_name"] = " Natural Alignment Crystal ", ["prio"] = " Prio:Sha",},
{["loot_id"] = "23036", ["loot_name"] = " Necklace of Necropsy ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "21678", ["loot_name"] = " Necklace of Purity ", ["prio"] = " Prio:Dru, Mag, Pri, Wlk",},
{["loot_id"] = "19379", ["loot_name"] = " Neltharion's Tear ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "21856", ["loot_name"] = " Neretzek, The Blood Drinker ", ["prio"] = " Prio:War (PvP)",},
{["loot_id"] = "22812", ["loot_name"] = " Nerubian Slavemaker ", ["prio"] = " Prio:Hnt",},
{["loot_id"] = "23029", ["loot_name"] = " Noth's Frigid Heart ", ["prio"] = " Prio:Dru, Pri, ?",},
{["loot_id"] = "18822", ["loot_name"] = " Obsidian Edged Blade ", ["prio"] = " Prio: Rank 8+",},
{["loot_id"] = "19137", ["loot_name"] = " Onslaught Girdle ", ["prio"] = " Prio:War",},
{["loot_id"] = "21691", ["loot_name"] = " Ooze-ridden Gauntlets ", ["prio"] = " Prio:War",},
{["loot_id"] = "21639", ["loot_name"] = " Pauldrons of the Unrelenting ", ["prio"] = " Prio:War",},
{["loot_id"] = "22947", ["loot_name"] = " Pendant of Forgotten Names ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "19371", ["loot_name"] = " Pendant of the Fallen Dragon ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "21700", ["loot_name"] = " Pendant of the Qiraji Guardian ", ["prio"] = " Prio:Frl, War",},
{["loot_id"] = "18816", ["loot_name"] = " Perdition's Blade ", ["prio"] = " Prio: Rog, Tnk",},
{["loot_id"] = "21685", ["loot_name"] = " Petrified Scarab ", ["prio"] = " Prio:All",},
{["loot_id"] = "23000", ["loot_name"] = " Plated Abomination Ribcage ", ["prio"] = " Prio:War",},
{["loot_id"] = "23020", ["loot_name"] = " Polar Helmet ", ["prio"] = " Prio:Frl, Rog",},
{["loot_id"] = "23035", ["loot_name"] = " Preceptor's Hat ", ["prio"] = " Prio:Bal, Mag, Pri, Wlk",},
{["loot_id"] = "19377", ["loot_name"] = " Prestor's Talisman of Connivery ", ["prio"] = " Prio:Hnt, Rog",},
{["loot_id"] = "19401", ["loot_name"] = " Primalist's Linked Legguards ", ["prio"] = " Prio:Hnt",},
{["loot_id"] = "19393", ["loot_name"] = " Primalist's Linked Waistguard ", ["prio"] = " Prio:Hnt",},
{["loot_id"] = "19382", ["loot_name"] = " Pure Elementium Band ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "21602", ["loot_name"] = " Qiraji Execution Bracers ", ["prio"] = " Prio:Rog, Tnk",},
{["loot_id"] = "18821", ["loot_name"] = " Quick Strike Ring ", ["prio"] = " Prio: Rog, Fur > Tnk ",},
{["loot_id"] = "21648", ["loot_name"] = " Recomposed Boots ", ["prio"] = " Prio:Dru, Mag, Pri, Pal, Wlk",},
{["loot_id"] = "19348", ["loot_name"] = " Red Dragonscale Protector ", ["prio"] = " Prio:Pal",},
{["loot_id"] = "21609", ["loot_name"] = " Regenerating Belt of Vek'nilash ", ["prio"] = " Prio:Dru, Pal",},
{["loot_id"] = "19395", ["loot_name"] = " Rejuvenating Gem ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "22983", ["loot_name"] = " Rime Covered Mantle ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "19397", ["loot_name"] = " Ring of Blackrock ", ["prio"] = " Prio:Dru, Mag, Pri, Pal, Wlk",},
{["loot_id"] = "21601", ["loot_name"] = " Ring of Emperor Vek'lor ", ["prio"] = " Prio:Frl, War",},
{["loot_id"] = "19147", ["loot_name"] = " Ring of Spell Power ", ["prio"] = " Prio:Mag, Shd, Wlk",},
{["loot_id"] = "23037", ["loot_name"] = " Ring of Spiritual Fervor ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "21707", ["loot_name"] = " Ring of Swarming Thought ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "21681", ["loot_name"] = " Ring of the Devoured ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "23237", ["loot_name"] = " Ring of the Eternal Flame ", ["prio"] = " Prio:Mag",},
{["loot_id"] = "21596", ["loot_name"] = " Ring of the Godslayer ", ["prio"] = " Prio:Frl, Hnt, Rog, War",},
{["loot_id"] = "21620", ["loot_name"] = " Ring of the Martyr ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "21677", ["loot_name"] = " Ring of the Qiraji Fury ", ["prio"] = " Prio:War",},
{["loot_id"] = "19438", ["loot_name"] = " Ringo's Blizzard Boots ", ["prio"] = " Prio:Mag",},
{["loot_id"] = "21836", ["loot_name"] = " Ritssyn's Ring of Chaos ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "19145", ["loot_name"] = " Robe of Volatile Power ", ["prio"] = " Prio:Mag, Shd, Wlk",},
{["loot_id"] = "21671", ["loot_name"] = " Robes of the Battleguard ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "21663", ["loot_name"] = " Robes of the Guardian Saint ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "21696", ["loot_name"] = " Robes of the Triumvirate ", ["prio"] = " Prio:Dru, Mag, Pri, Pal, Wlk",},
{["loot_id"] = "21598", ["loot_name"] = " Royal Qiraji Belt ", ["prio"] = " Prio:War",},
{["loot_id"] = "21597", ["loot_name"] = " Royal Scepter of Vek'lor ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "19340", ["loot_name"] = " Rune of Metamorphosis ", ["prio"] = " Prio:Dru",},
{["loot_id"] = "19144", ["loot_name"] = " Sabatons of the Flamewalker ", ["prio"] = " Prio:Hnt",},
{["loot_id"] = "23023", ["loot_name"] = " Sadist's Collar ", ["prio"] = " Prio:Frl, Hnt, Rog, War",},
{["loot_id"] = "18875", ["loot_name"] = " Salamander Scale Pants ", ["prio"] = " Prio:Dru, Pal",},
{["loot_id"] = "23049", ["loot_name"] = " Sapphiron's Left Eye ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "23048", ["loot_name"] = " Sapphiron's Right Eye ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "18809", ["loot_name"] = " Sash of Whispered Secrets ", ["prio"] = " Prio:Shd, Wlk",},
{["loot_id"] = "21668", ["loot_name"] = " Scaled Leggings of Qiraji Fury ", ["prio"] = " Prio:??",},
{["loot_id"] = "21625", ["loot_name"] = " Scarab Brooch ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "21839", ["loot_name"] = " Scepter of the False Prophet ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "17110", ["loot_name"] = " Seal of the Archmagus ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "23025", ["loot_name"] = " Seal of the Damned ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "22815", ["loot_name"] = " Severance ", ["prio"] = " Prio:Hnt, War",},
{["loot_id"] = "19355", ["loot_name"] = " Shadow Wing Focus Staff ", ["prio"] = " Prio:Bal, Mag, Pri, Wlk",},
{["loot_id"] = "17074", ["loot_name"] = " Shadowstrike ", ["prio"] = " Prio:Hnt, War",},
{["loot_id"] = "21891", ["loot_name"] = " Shard of the Fallen Star ", ["prio"] = " Prio:All",},
{["loot_id"] = "17082", ["loot_name"] = " Shard of the Flame ", ["prio"] = " Prio:All",},
{["loot_id"] = "21622", ["loot_name"] = " Sharpened Silithid Femur ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "22819", ["loot_name"] = " Shield of Condemnation ", ["prio"] = " Prio:Pal",},
{["loot_id"] = "19391", ["loot_name"] = " Shimmering Geta ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "23045", ["loot_name"] = " Shroud of Dominion ", ["prio"] = " Prio:Hnt, Rog, War",},
{["loot_id"] = "19430", ["loot_name"] = " Shroud of Pure Thought ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "23018", ["loot_name"] = " Signet of the Fallen Defender ", ["prio"] = " Prio:Frl, War",},
{["loot_id"] = "21652", ["loot_name"] = " Silithid Carapace Chestguard ", ["prio"] = " Prio:War",},
{["loot_id"] = "21673", ["loot_name"] = " Silithid Claw ", ["prio"] = " Prio:Hnt",},
{["loot_id"] = "23041", ["loot_name"] = " Slayer's Crest ", ["prio"] = " Prio:Hnt, Rog, War",},
{["loot_id"] = "21626", ["loot_name"] = " Slime-coated Leggings ", ["prio"] = " Prio:Hnt",},
{["loot_id"] = "18878", ["loot_name"] = " Sorcerous Dagger ", ["prio"] = " Prio:Dru, Mag, Pri, Pal, Wlk",},
{["loot_id"] = "22799", ["loot_name"] = " Soulseeker ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "22811", ["loot_name"] = " Soulstring ", ["prio"] = " Prio:Hnt, Rog, War",},
{["loot_id"] = "17104", ["loot_name"] = " Spinal Reaper ", ["prio"] = " Prio:Hnt, War",},
{["loot_id"] = "19335", ["loot_name"] = " SpineShatter ", ["prio"] = " Prio:War",},
{["loot_id"] = "22801", ["loot_name"] = " Spire of Twilight ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "18842", ["loot_name"] = " Staff of Dominance ", ["prio"] = " Prio:Mag, Shd, Wlk",},
{["loot_id"] = "21128", ["loot_name"] = " Staff of the Qiraji Prophets ", ["prio"] = " Prio:Bal, Mag, Pri, Pal, Wlk",},
{["loot_id"] = "19356", ["loot_name"] = " Staff of the Shadow Flame ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "23053", ["loot_name"] = " Stormrage's Talisman of Seething ", ["prio"] = " Prio:Hnt, Rog, War",},
{["loot_id"] = "17069", ["loot_name"] = " Striker's Mark ", ["prio"] = " Prio:Rog, War",},
{["loot_id"] = "23238", ["loot_name"] = " Stygian Buckler ", ["prio"] = " Prio:War",},
{["loot_id"] = "19431", ["loot_name"] = " Styleen's Impeding Scarab ", ["prio"] = " Prio:War",},
{["loot_id"] = "18820", ["loot_name"] = " Talisman of Ephemeral Power ", ["prio"] = " Prio:Mag, Shd, Wlk",},
{["loot_id"] = "19396", ["loot_name"] = " Taut Dragonhide Belt ", ["prio"] = " Prio:Frl, Rog",},
{["loot_id"] = "19390", ["loot_name"] = " Taut Dragonhide Gloves ", ["prio"] = " Prio:Dru, Pal",},
{["loot_id"] = "19389", ["loot_name"] = " Taut Dragonhide Shoulderpads ", ["prio"] = " Prio:Frl, Rog",},
{["loot_id"] = "21694", ["loot_name"] = " Ternary Mantle ", ["prio"] = " Prio:Pri",},
{["loot_id"] = "19337", ["loot_name"] = " The Black Book ", ["prio"] = " Prio:Wlk",},
{["loot_id"] = "23558", ["loot_name"] = " The Burrower's Shell ", ["prio"] = " Prio:All",},
{["loot_id"] = "22808", ["loot_name"] = " The Castigator ", ["prio"] = " Prio:War",},
{["loot_id"] = "22988", ["loot_name"] = " The End of Dreams ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "18646", ["loot_name"] = " The Eye of Divinity ", ["prio"] = " Prio:Pri",},
{["loot_id"] = "23039", ["loot_name"] = " The Eye of Nerub ", ["prio"] = " Prio:Hnt",},
{["loot_id"] = "23043", ["loot_name"] = " The Face of Death ", ["prio"] = " Prio:War",},
{["loot_id"] = "23577", ["loot_name"] = " The Hungering Cold ", ["prio"] = " Prio:Rog, War",},
{["loot_id"] = "22520", ["loot_name"] = " The Phylactery of Kel'Thuzad ", ["prio"] = " Prio:Hnt, Mag, Rog, War, Wlk",},
{["loot_id"] = "22818", ["loot_name"] = " The Plague Bearer ", ["prio"] = " Prio:War",},
{["loot_id"] = "23046", ["loot_name"] = " The Restrained Essence of Sapphiron ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "23021", ["loot_name"] = " The Soul Harvester's Bindings ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "19334", ["loot_name"] = " The Untamed Blade ", ["prio"] = " Prio:War (PvP)",},
{["loot_id"] = "19380", ["loot_name"] = " Therazane's Link ", ["prio"] = " Prio:Hnt",},
{["loot_id"] = "21675", ["loot_name"] = " Thick Qirajihide Belt ", ["prio"] = " Prio:Frl, Rog",},
{["loot_id"] = "22935", ["loot_name"] = " Touch of Frost ", ["prio"] = " Prio:All",},
{["loot_id"] = "22810", ["loot_name"] = " Toxin Injector ", ["prio"] = " Prio:Hnt, Rog, War",},
{["loot_id"] = "21692", ["loot_name"] = " Triad Girdle ", ["prio"] = " Prio:War",},
{["loot_id"] = "21687", ["loot_name"] = " Ukko's Ring of Darkness ", ["prio"] = " Prio:Wlk",},
{["loot_id"] = "21579", ["loot_name"] = " Vanquished Tentacle of C'Thun ", ["prio"] = " Prio:All",},
{["loot_id"] = "21599", ["loot_name"] = " Vek'lor's Gloves of Devastation ", ["prio"] = " Prio:Hnt",},
{["loot_id"] = "21680", ["loot_name"] = " Vest of Swift Execution ", ["prio"] = " Prio:Frl",},
{["loot_id"] = "22820", ["loot_name"] = " Wand of Fates ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "21603", ["loot_name"] = " Wand of Qiraji Nobility ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "23009", ["loot_name"] = " Wand of the Whispering Dead ", ["prio"] = " Prio:Pri",},
{["loot_id"] = "23027", ["loot_name"] = " Warmth of Forgiveness ", ["prio"] = " Prio:Dru, Pri, Pal",},
{["loot_id"] = "21617", ["loot_name"] = " Wasphide Gauntlets ", ["prio"] = " Prio:Dru, Pal",},
{["loot_id"] = "22806", ["loot_name"] = " Widow's Remorse ", ["prio"] = " Prio:Rog, War",},
{["loot_id"] = "18810", ["loot_name"] = " Wild Growth Spaulders ", ["prio"] = " Prio:Dru, Pal",},
{["loot_id"] = "21610", ["loot_name"] = " Wormscale Blocker ", ["prio"] = " Prio:Pal",},
{["loot_id"] = "22807", ["loot_name"] = " Wraith Blade ", ["prio"] = " Prio:Mag, Wlk",},
{["loot_id"] = "19146", ["loot_name"] = " Wristguards of Stability ", ["prio"] = " Prio:War",},
{["loot_id"] = "18812", ["loot_name"] = " Wristguards of True Flight ", ["prio"] = " Prio:Hnt, War",},
{["loot_id"] = "22936", ["loot_name"] = " Wristguards of Vengeance ", ["prio"] = " Prio:War",},
}